Apriori

In [1]:
dataset=[['Milk', 'Onion', 'Nutmeg', 'Kidney Beans', 'Eggs', 'Yogurt'],
         ['Dill', 'Onion', 'Nutmeg', 'Kidney Beans', 'Eggs', 'Yogurt'],
         ['Milk', 'Apple', 'Kidney Beans', 'Eggs'],
         ['Milk', 'Unicorn', 'Corn', 'Kidney Beans', 'Yogurt'],
         ['Corn', 'Onion', 'Onion', 'Kidney Beans', 'Ice cream', 'Eggs']]

In [2]:
import pandas as pd;
from mlxtend.preprocessing import TransactionEncoder

In [3]:
dataset

[['Milk', 'Onion', 'Nutmeg', 'Kidney Beans', 'Eggs', 'Yogurt'],
 ['Dill', 'Onion', 'Nutmeg', 'Kidney Beans', 'Eggs', 'Yogurt'],
 ['Milk', 'Apple', 'Kidney Beans', 'Eggs'],
 ['Milk', 'Unicorn', 'Corn', 'Kidney Beans', 'Yogurt'],
 ['Corn', 'Onion', 'Onion', 'Kidney Beans', 'Ice cream', 'Eggs']]

In [4]:
te = TransactionEncoder()
te_ary = te.fit(dataset).transform(dataset)

In [5]:
df= pd.DataFrame(te_ary, columns=te.columns_)
df

,Apple,Corn,Dill,Eggs,Ice cream,Kidney Beans,Milk,Nutmeg,Onion,Unicorn,Yogurt
0,False,False,False,True,False,True,True,True,True,False,True
1,False,False,True,True,False,True,False,True,True,False,True
2,True,False,False,True,False,True,True,False,False,False,False
3,False,True,False,False,False,True,True,False,False,True,True
4,False,True,False,True,True,True,False,False,True,False,False

In [6]:
from mlxtend.frequent_patterns import apriori

frequent_itemsets = apriori(df, min_support=0.6,use_colnames=True)
frequent_itemsets

    support                     itemsets
0       0.8                       (Eggs)
1       1.0               (Kidney Beans)
2       0.6                       (Milk)
3       0.6                      (Onion)
4       0.6                     (Yogurt)
5       0.8         (Kidney Beans, Eggs)
6       0.6                (Onion, Eggs)
7       0.6         (Kidney Beans, Milk)
8       0.6        (Onion, Kidney Beans)
9       0.6       (Yogurt, Kidney Beans)
10      0.6  (Onion, Kidney Beans, Eggs)

Asscociation Ruole

In [7]:
from mlxtend.frequent_patterns import association_rules
res =  association_rules(frequent_itemsets ,metric="confidence",min_threshold=0.7)
res

F:\New folder (2)\anaconda\lib\site-packages\ipykernel\ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,zhangs_metric
0,(Kidney Beans),(Eggs),1.0,0.8,0.8,0.80,1.00,0.00,1.0,0.0
1,(Eggs),(Kidney Beans),0.8,1.0,0.8,1.00,1.00,0.00,inf,0.0
2,(Onion),(Eggs),0.6,0.8,0.6,1.00,1.25,0.12,inf,0.5
3,(Eggs),(Onion),0.8,0.6,0.6,0.75,1.25,0.12,1.6,1.0
4,(Milk),(Kidney Beans),0.6,1.0,0.6,1.00,1.00,0.00,inf,0.0
5,(Onion),(Kidney Beans),0.6,1.0,0.6,1.00,1.00,0.00,inf,0.0
6,(Yogurt),(Kidney Beans),0.6,1.0,0.6,1.00,1.00,0.00,inf,0.0
7,"(Onion, Kidney Beans)",(Eggs),0.6,0.8,0.6,1.00,1.25,0.12,inf,0.5
8,"(Onion, Eggs)",(Kidney Beans),0.6,1.0,0.6,1.00,1.00,0.00,inf,0.0
9,"(Kidney Beans, Eggs)",(Onion),0.8,0.6,0.6,0.75,1.25,0.12,1.6,1.0
10,(Onion),"(Kidney Beans, Eggs)",0.6,0.8,0.6,1.00,1.25,0.12,inf,0.5
11,(Eggs),"(Onion, Kidney Beans)",0.8,0.6,0.6,0.75,1.25,0.12,1.6,1.0

In [8]:
res1 = res[['antecedents','consequents','support','confidence','lift']]
res1

F:\New folder (2)\anaconda\lib\site-packages\ipykernel\ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

              antecedents            consequents  support  confidence  lift
0          (Kidney Beans)                 (Eggs)      0.8        0.80  1.00
1                  (Eggs)         (Kidney Beans)      0.8        1.00  1.00
2                 (Onion)                 (Eggs)      0.6        1.00  1.25
3                  (Eggs)                (Onion)      0.6        0.75  1.25
4                  (Milk)         (Kidney Beans)      0.6        1.00  1.00
5                 (Onion)         (Kidney Beans)      0.6        1.00  1.00
6                (Yogurt)         (Kidney Beans)      0.6        1.00  1.00
7   (Onion, Kidney Beans)                 (Eggs)      0.6        1.00  1.25
8           (Onion, Eggs)         (Kidney Beans)      0.6        1.00  1.00
9    (Kidney Beans, Eggs)                (Onion)      0.6        0.75  1.25
10                (Onion)   (Kidney Beans, Eggs)      0.6        1.00  1.25
11                 (Eggs)  (Onion, Kidney Beans)      0.6        0.75  1.25

In [9]:
res2 = res1[res1['confidence'] >=1]
res2

F:\New folder (2)\anaconda\lib\site-packages\ipykernel\ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

              antecedents           consequents  support  confidence  lift
1                  (Eggs)        (Kidney Beans)      0.8         1.0  1.00
2                 (Onion)                (Eggs)      0.6         1.0  1.25
4                  (Milk)        (Kidney Beans)      0.6         1.0  1.00
5                 (Onion)        (Kidney Beans)      0.6         1.0  1.00
6                (Yogurt)        (Kidney Beans)      0.6         1.0  1.00
7   (Onion, Kidney Beans)                (Eggs)      0.6         1.0  1.25
8           (Onion, Eggs)        (Kidney Beans)      0.6         1.0  1.00
10                (Onion)  (Kidney Beans, Eggs)      0.6         1.0  1.25

!pip install pandas

In [10]:
!pip install apriori

F:\New folder (2)\anaconda\lib\site-packages\ipykernel\ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

Requirement already satisfied: apriori in f:\new folder (2)\anaconda\lib\site-packages (1.0.0)

In [11]:
!pip install association_rules

F:\New folder (2)\anaconda\lib\site-packages\ipykernel\ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)
ERROR: Could not find a version that satisfies the requirement association_rules (from versions: none)
ERROR: No matching distribution found for association_rules

In [12]:
!pip install mlxtend

F:\New folder (2)\anaconda\lib\site-packages\ipykernel\ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

Requirement already satisfied: mlxtend in f:\new folder (2)\anaconda\lib\site-packages (0.23.1)
Requirement already satisfied: joblib>=0.13.2 in f:\new folder (2)\anaconda\lib\site-packages (from mlxtend) (0.17.0)
Requirement already satisfied: matplotlib>=3.0.0 in f:\new folder (2)\anaconda\lib\site-packages (from mlxtend) (3.3.2)
Requirement already satisfied: scipy>=1.2.1 in f:\new folder (2)\anaconda\lib\site-packages (from mlxtend) (1.5.2)
Requirement already satisfied: scikit-learn>=1.0.2 in f:\new folder (2)\anaconda\lib\site-packages (from mlxtend) (1.3.2)
Requirement already satisfied: pandas>=0.24.2 in f:\new folder (2)\anaconda\lib\site-packages (from mlxtend) (1.1.3)
Requirement already satisfied: numpy>=1.16.2 in f:\new folder (2)\anaconda\lib\site-packages (from mlxtend) (1.19.2)
Requirement already satisfied: cycler>=0.10 in f:\new folder (2)\anaconda\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (0.10.0)
Requirement already satisfied: certifi>=2020.06.20 in f:\new folder (2)\anaconda\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (2020.6.20)
Requirement already satisfied: pillow>=6.2.0 in f:\new folder (2)\anaconda\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (8.0.1)
Requirement already satisfied: kiwisolver>=1.0.1 in f:\new folder (2)\anaconda\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (1.3.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3 in f:\new folder (2)\anaconda\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (2.4.7)
Requirement already satisfied: python-dateutil>=2.1 in f:\new folder (2)\anaconda\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (2.8.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in f:\new folder (2)\anaconda\lib\site-packages (from scikit-learn>=1.0.2->mlxtend) (2.1.0)
Requirement already satisfied: pytz>=2017.2 in f:\new folder (2)\anaconda\lib\site-packages (from pandas>=0.24.2->mlxtend) (2020.1)
Requirement already satisfied: six in f:\new folder (2)\anaconda\lib\site-packages (from cycler>=0.10->matplotlib>=3.0.0->mlxtend) (1.15.0)